name: Daily with gha-yarn-cache

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Test
      run: yarn test
  
  build2:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Test
      run: yarn test2
  
  ##################################
  ### Run when a push failed ###
  ##################################
  restart_when_failed:
    name: Restarts the pushed run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && failure()
    needs: ["build", "build2"]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/FinbertMDS/AwesomeTSProject/actions/workflows/8343760/dispatches \
          -d '{"ref": "${{ github.ref }}" }'